// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tcc_lang_backend.DB;

namespace tcc_lang_backend.Migrations
{
    [DbContext(typeof(TccDbContext))]
    [Migration("20190924214308_migration_remove_word_section")]
    partial class migration_remove_word_section
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("tcc_lang_backend.DB.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("tcc_lang_backend.DB.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FlashcardId");

                    b.Property<string>("Title");

                    b.Property<string>("Words");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("tcc_lang_backend.DB.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fullname")
                        .IsRequired();

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("tcc_lang_backend.DB.Text", b =>
                {
                    b.HasOne("tcc_lang_backend.DB.Flashcard", "Flashcard")
                        .WithMany()
                        .HasForeignKey("FlashcardId");
                });
#pragma warning restore 612, 618
        }
    }
}
