// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tcc_lang_backend.DB;

namespace tcc_lang_backend.Migrations
{
    [DbContext(typeof(TccDbContext))]
    [Migration("20190921153421_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("tcc_lang_backend.DB.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("tcc_lang_backend.DB.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fullname");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("tcc_lang_backend.DB.WordSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsPressed");

                    b.Property<int?>("TextId");

                    b.Property<string>("Word");

                    b.HasKey("Id");

                    b.HasIndex("TextId");

                    b.ToTable("WordSections");
                });

            modelBuilder.Entity("tcc_lang_backend.DB.WordSection", b =>
                {
                    b.HasOne("tcc_lang_backend.DB.Text", "Text")
                        .WithMany("WordSections")
                        .HasForeignKey("TextId");
                });
#pragma warning restore 612, 618
        }
    }
}
